mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: pojo

server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.129:3306/librarian?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: wu
    password: 123456
  redis:
    host: 192.168.2.129
    port: 6379
  flyway:
    #sql脚本的命名规范为：V+版本号(版本号的数字间以”.“或”_“分隔开)+双下划线(用来分隔版本号和描述)+文件描述+后缀名
    enabled: true #是否启用flyway
    encoding: UTF-8 #编码格式 默认UTF-8
    locations: classpath:db/migration #迁移sql脚本文件存放路径，默认db/migration
    sql-migration-prefix: V #迁移sql脚本文件名称的前缀，默认V
    sql-migration-separator: __ #迁移脚本文件名称的分隔符，默认2个下划线__
    validate-on-migrate: true #迁移时是否进行校验，默认true
    baseline-on-migrate: true #当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger2配置 防止报错

  mail:
    host: smtp.qq.com #配置服务器qq:smtp.qq.com,网易163:smtp.163.com
    username: xxx@xxx.com #配置公用发件人
    password: xxx #配置授权码，邮箱->设置->账户->pop3/SMTP服务：开启后会获得授权码
    default-encoding: UTF-8 #配置默认编码
    properties: #一些其他配置
      mail:
        smtp:
          ssl:
            trust: mail.163.com
          timeout: 10000
          connection-timeout: 10000
          write-timeout: 10000
          auth: true
          starttls:
            enable: false
            required: false
          sockFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

  rabbitmq:
    host: 192.168.2.129
    port: 5672
    username: admin
    password: admin
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: /
    #这个配置是保证消费者会消费消息，手动确认
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true

oss:
  qiniu:
    accessKey: xxx
    secretKey: xxx
    urlPre: xxx
    expiredSeconds: 3600
    bucketName: whx-librarian