mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: pojo

server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.254.128:3306/librarian?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: wu
    password: 123456
  redis:
    host: 192.168.254.128
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger2配置 防止报错

  mail:
    host: smtp.qq.com #配置服务器qq:smtp.qq.com,网易163:smtp.163.com
    username: 1978938887@qq.com #配置发件人
    password: qaujjphydhozehif #配置授权码，邮箱->设置->账户->pop3/SMTP服务：开启后会获得授权码
    default-encoding: UTF-8 #配置默认编码
    properties: #一些其他配置
      mail:
        smtp:
          ssl:
            trust: mail.163.com
          timeout: 10000
          connection-timeout: 10000
          write-timeout: 10000
          auth: true
          starttls:
            enable: false
            required: false
          sockFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

  rabbitmq:
    host: 192.168.254.128
    port: 5672
    username: admin
    password: admin
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: /
    #这个配置是保证消费者会消费消息，手动确认
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true